//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organisation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Organisation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Organisation ID=&quot;SEAB&quot; Name=&quot;Singapore Examinations and Assessment Board&quot;&gt;
        ///  &lt;Person&gt;
        ///    &lt;Name&gt;Tan Lay Choo (Ms)&lt;/Name&gt;
        ///    &lt;Sex&gt;F&lt;/Sex&gt;
        ///    &lt;Des&gt;Chief Executive&lt;/Des&gt;
        ///    &lt;Loc&gt;#A4-06&lt;/Loc&gt;
        ///    &lt;Tel&gt;63777698&lt;/Tel&gt;
        ///    &lt;Im&gt;SEAB/TanLayChoo.jpg&lt;/Im&gt;
        ///  &lt;/Person&gt;
        ///  &lt;Person&gt;
        ///    &lt;Name&gt;See Poh Tin Lynn (Ms)&lt;/Name&gt;
        ///    &lt;Sex&gt;F&lt;/Sex&gt;
        ///    &lt;Des&gt;Personal Assistant to Chief Executive&lt;/Des&gt;
        ///    &lt;Loc&gt;#A4-05&lt;/Loc&gt;
        ///    &lt;Tel&gt;63777698&lt;/Tel&gt;
        ///    &lt;Im&gt;SEAB/LynnSee.jpg&lt;/Im&gt;
        ///  &lt;/Person&gt;
        ///  &lt;Division Name=&quot;Corporat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ORGXml {
            get {
                return ResourceManager.GetString("ORGXml", resourceCulture);
            }
        }
    }
}
