//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEAB_EXAM
    {
        public string EXAM_ID { get; set; }
        public int SCH_ID { get; set; }
        public string SUBJ_CODE { get; set; }
        public int SEAT_MAX { get; set; }
        public Nullable<int> SEAT_USED { get; set; }
        public System.DateTime EXAM_DATE { get; set; }
        public System.DateTime START_TIME { get; set; }
        public System.DateTime END_TIME { get; set; }
        public string EXAM_TIMETABLE { get; set; }
    }
}
