//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEAB_SCHOOL
    {
        public int SCH_ID { get; set; }
        public string SCH_NAME { get; set; }
        public decimal SCH_LOC_LAT { get; set; }
        public decimal SCH_LOC_LONG { get; set; }
    }
}
