//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEAB_SUBJECT
    {
        public string SUBJ_CODE { get; set; }
        public string SUBJ_NAME { get; set; }
        public string SYLLABUS { get; set; }
    }
}
